webtalk_init -webtalk_dir C:/Users/ddrew/Documents/ECGR 2181/computer_assignment_3/computer_assignment_3/computer_assignment_3.sim/sim_1/behav/xsim/xsim.dir/top_td_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec  4 13:36:40 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d5574b77-d9f6-4a73-9356-9b78d36a3dbe" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e6245e8e62824f27b22a345d7c9fb4a0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.13_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8412_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3747788608 -regid "" -xml C:/Users/ddrew/Documents/ECGR 2181/computer_assignment_3/computer_assignment_3/computer_assignment_3.sim/sim_1/behav/xsim/xsim.dir/top_td_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ddrew/Documents/ECGR 2181/computer_assignment_3/computer_assignment_3/computer_assignment_3.sim/sim_1/behav/xsim/xsim.dir/top_td_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ddrew/Documents/ECGR 2181/computer_assignment_3/computer_assignment_3/computer_assignment_3.sim/sim_1/behav/xsim/xsim.dir/top_td_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
